### ISSUE TITLE
am I right in thinking this board has WiFi built in?

### ISSUE THREAD

**Issue by mynameispaulkeenan** [radxa-build/rock-3c#7]

**Comment by mynameispaulkeenan** [comment]
I just installed and was expecting to see some wireless access points to connect through but nothing, I did however haul my trusty old edimax usb dongle out of retirement  which solved it for the time being.

**Comment by mynameispaulkeenan** [comment]
Excuse my uselessness, as I'm on my phone and feeling old!

**Comment by RadxaYuntian** [comment]
We have updated the wireless module on 3C recently. Please check if your wireless module comes with a Radxa sticker. If you want to be sure you can also remove the sticker, and the metal shield should not have any text engraved on it. The original wireless module will have either AP6256 or CM256 engraved on it instead of a sticker.

If you are indeed having the updated wireless module, then the current released image does not work with it. We currently have a RC image that support this new module:

https://github.com/radxa-build/rock-3c/releases/download/b42/rock-3c_debian_bullseye_xfce_b42.img.xz

**Comment by csvke** [comment]
> We have updated the wireless module on 3C recently. Please check if your wireless module comes with a Radxa sticker. If you want to be sure you can also remove the sticker, and the metal shield should not have any text engraved on it. The original wireless module will have either AP6256 or CM256 engraved on it instead of a sticker.
> 
> If you are indeed having the updated wireless module, then the current released image does not work with it. We currently have a RC image that support this new module:
> 
> https://github.com/radxa-build/rock-3c/releases/download/b42/rock-3c_debian_bullseye_xfce_b42.img.xz

Can you guys please have some update on your site's wiki because it is very frustrating to have the basics not working because of unclear documentations. (maybe a caution box and ask users to download the b42 build?)

Your products are great but it's the software and documentations that sets them apart. 
https://wiki.radxa.com/Rock3/3c

**Comment by RadxaYuntian** [comment]
Wiki is deprecated. The [download page](https://docs.radxa.com/en/rock3/images?model=ROCK+3C) in the new documentation site is pointing to the b42 image, which is also the latest release listed on GitHub.

Can you tell me what page still contains the older version? 3C was not listed in Wiki's download page.

**Comment by csvke** [comment]
> Wiki is deprecated. The [download page](https://docs.radxa.com/en/rock3/images?model=ROCK+3C) in the new documentation site is pointing to the b42 image, which is also the latest release listed on GitHub.
> 
> Can you tell me what page still contains the older version? 3C was not listed in Wiki's download page.

https://wiki.radxa.com/Rock3/Debian#List_of_boards_supported

Sorry I think I got misguided when I see the list of board supported which does not include Rock 3C (which is not true? You guys have been building Debian for Rock 3c)

**Comment by RadxaYuntian** [comment]
Wiki is deprecated and now contains a lot of out-dated info. As long as you follow docs.radxa.com you should be fine.

**Comment by RadxaYuntian** [comment]
Close as original issue was solved by b42 being officially released.
